plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.undefinedbehaviourgames.grizzly'
    compileSdk 36

    defaultConfig {
        applicationId "com.undefinedbehaviourgames.grizzly"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        android.defaultConfig.manifestPlaceholders = [
                'appAuthRedirectScheme': 'com.undefinedbehaviourgames.grizzly'
        ]
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {

    implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
    implementation 'com.github.scribejava:scribejava-apis:6.4.1'
    implementation 'com.squareup.retrofit2:converter-gson:3.0.0'
    implementation 'com.squareup.retrofit2:retrofit:3.0.0'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'commons-codec:commons-codec:1.22.0'
    implementation 'net.openid:appauth:0.11.1'
    implementation 'com.google.code.gson:gson:2.14.0'
//    implementation 'com.android.support:appcompat-v7:25.0.1'
    implementation 'com.google.android.gms:play-services-auth:21.5.1'
//    implementation 'pub.devrel:easypermissions:0.3.0'
    implementation('com.google.api-client:google-api-client-android:1.22.0') {
        exclude group: 'org.apache.httpcomponents'
    }
    implementation('com.google.apis:google-api-services-youtube:v3-rev183-1.22.0') {
        exclude group: 'org.apache.httpcomponents'
    }
    implementation libs.appcompat
    implementation libs.activity
    implementation libs.constraintlayout
    implementation files('../login-with-amazon-sdk.jar')
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}